### ISSUE TITLE
Event Schedule Page

### ISSUE THREAD

**Issue by tjmonsi** [gdgphilippines/devfest#10]
Show event schedule page that allows bookmark of sessions. 
- requirement: Design for event schedule page, and schedule 
- functionalities (later): bookmark of sessions #11
- show own schedule #14

**Comment by juvarabrera** [comment]
Schedule Page Design
[schedule.zip](https://github.com/gdgphilippines/devfest/files/1298382/schedule.zip)

1. Consider the css.
2. See the effect when in mobile.
3. Add Schedule in nav bar.

**Comment by juvarabrera** [comment]
Tags:
`<span class="{{color}} tag">{{tag_name}}</span>`

tag_name | color
----------------------
- Core Technologies | blue
- Emerging Technologies | red
- Dev Ops / Cloud | yellow black-text
- Design / Distribution | green
