### ISSUE TITLE
Font color in Tickets page

### ISSUE THREAD

**Issue by juvarabrera** [gdgphilippines/devfest#101]
### Description
Font color in Ticket Details section in Tickets page is incorrect

### Expected outcome

Font color should be white
![image](https://user-images.githubusercontent.com/13174418/30274387-c37909aa-972f-11e7-9f46-6290b3eca42a.png)

### Actual outcome

Font color is dark gray.
![image](https://user-images.githubusercontent.com/13174418/30274374-b7751b6c-972f-11e7-9838-c0125ef79a91.png)

### Live Demo

N/A

### Steps to reproduce

1. Change font colors from dark gray to white

### Browsers Affected

- [ x] Chrome
- [x ] Firefox
- [x ] Safari 9
- [x ] Safari 8
- [x ] Safari 7
- [x ] Edge
- [x ] IE 11
- [x ] IE 10

**Comment by tjmonsi** [comment]
I think i broke this. I'll fix it
