### ISSUE TITLE
Icon size

### ISSUE THREAD

**Issue by AriadnaSumondong** [gdgphilippines/devfest#107]
### Description
Different sizes

### Browsers Affected

- [ ] Chrome
- [ ] Edge
![edge size](https://user-images.githubusercontent.com/31662702/30280005-3d3e85ce-9741-11e7-8f74-72cf576716c1.png)
![googlesize](https://user-images.githubusercontent.com/31662702/30280006-3d42f122-9741-11e7-8752-cc0017e5fa09.png)

**Comment by tjmonsi** [comment]
I see.. thanks for the headsup

**Comment by tjmonsi** [comment]
Fixed in #115

**Comment by jkga** [comment]
Icons in edge are still too small

![](https://lh3.googleusercontent.com/IPB8FRtUOBehs_L7Usvkc83wW7cPnz6OoEUq_JMZ8YA0rN36V1-tgt7rq64k_2bnlTOjzzY_8vfFA4skQcdSz0oIPS3chjq4QVA32i8awjOjx8wiPs1W0KQDi6C_FcEY2dD8uv5QmBZYYJo4ziT3kql37opYCHyd2hr0X52fIrbe2m7OYJr810lLN3jJ0UAh0P1_hNhb0xZdbT_tqf0CRDUqea4uZqDmTGneOOPHwG13hbbHtoDQKcE8XYwOmp-nzto1kiFB7ZzD55VbCi8shbH1sxZUp2DGX5WcX7Zgx1u3BpwkpObtJp6l1zp5K7e9XyTI-uEQ-F2lcYmZ-otjcQTrm7pXSiW5t10XDZs94jKiqo_yH22eTaPrUOXGB8ffH6DAkFifQmjC8Z4Kj-U52ewUKysjYl3wj-SGe_8QnQva6Y6QCcqgkv5ZYFmk_0o5Ss43mYFygp9SUpTKWg6WCvnvrNK3fqAan8vYMbNn9wYuxKIYIRrIjlQLMtl43jRbL1m7MG5IFbusR64oO5e75aDPFx0O_n9dOyg1SoAHBCADrOf2qkhrH50QVnfQydHLRsThgYtO0W4GzNAzrGDCeQiow9SMGU6c9UmRlds9VwiByDaPNzZDbV-Q-pDO0w4AnghSCo_sCm1mWtxh8zhNg3-KPuC8Y6v8q72AytmQKcYlHQ=w1133-h637-no)

**Comment by tjmonsi** [comment]
I'll check it again once I am back. Please reopen the issue if it's not working
