### ISSUE TITLE
Icon size

### ISSUE THREAD

**Issue by AriadnaSumondong** [gdgphilippines/devfest#108]
### Description
Different sizes

### Browsers Affected

- [ ] Chrome
- [ ] Edge
![edgefreebies](https://user-images.githubusercontent.com/31662702/30280293-f970022c-9741-11e7-811d-1f750247ed4f.png)
![googlefreebies](https://user-images.githubusercontent.com/31662702/30280294-f97e5e80-9741-11e7-85b1-3dc9a07e9ac4.png)

**Comment by tjmonsi** [comment]
Hmmm... can you check it again (refresh on edge). I dunno why it is not showing right on your side while mine is fixed :(

Can someone also check it on their side?

**Comment by AriadnaSumondong** [comment]
same pa din po. maliliit pa din yung icons. pati po sa payment maliit din

**Comment by jkga** [comment]
Experiencing the same issue with my device.
I noticed that when I  **remove the icon** in the developer console in Edge, **then pressing Ctrl + z** 
it displays the icon properly. It might be an issue in css as MS [flexbox rules](https://msdn.microsoft.com/en-us/library/dn265027(v=vs.85).aspx) have been updated

**Comment by tjmonsi** [comment]
What do you mean remove the icon?

**Comment by tjmonsi** [comment]
Connected to #107
