### ISSUE TITLE
Venue section in Home page

### ISSUE THREAD

**Issue by juvarabrera** [gdgphilippines/devfest#111]
### Description
Adding venue section in home page and venue in landing page.

### Live Demo

![image](https://user-images.githubusercontent.com/13174418/30302341-fd901774-9792-11e7-9242-7ed74593760c.png)

![image](https://user-images.githubusercontent.com/13174418/30302082-50f5c6b8-9791-11e7-90e3-9960be45b5f9.png)

### Steps to reproduce

1. Insert venue section below Speakers section
2. Add venue beside date in devfest-landing-page 
[venue.zip](https://github.com/gdgphilippines/devfest/files/1294381/venue.zip)

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by tjmonsi** [comment]
Adding it up now. Thanks @juvarabrera

**Comment by juvarabrera** [comment]
I have additional enhancement pa pala sa devfest-landing-page. Updating first post...

**Comment by juvarabrera** [comment]
Updated! :) I also updated the zip file

**Comment by tjmonsi** [comment]
What's the thing you have updated? @juvarabrera
