### ISSUE TITLE
Howard Dy Go Photo

### ISSUE THREAD

**Issue by juvarabrera** [gdgphilippines/devfest#113]
### Description
Changed Howard Go's Photo

### Steps to reproduce
1. Use the following photo below for Howard Go.
![howard go](https://user-images.githubusercontent.com/13174418/30302475-eb58cca8-9793-11e7-8e10-2133db0ab07b.jpg)

**Comment by tjmonsi** [comment]
On next push to master in devfestfilesph-2017
