### ISSUE TITLE
gdg-logo opacity error

### ISSUE THREAD

**Issue by jkga** [gdgphilippines/devfest#133]
### Description
**gdg-logo fade effect** on scroll down is not working in other pages except in the home page

### Expected outcome
there must be a gdg-logo fade effect for both **SPEAKERS** and **GET TICKETS** pages

### Actual outcome

Effect works only in home page

### Live Demo
N/A

### Steps to reproduce
1. Open the page in a web browser.
2. **Scroll down** to **About conference** section
3. Click **GET TICKETS** navigation button on header
4. Scroll down to **Ticket details** section

### Browsers Affected

- [x ] Chrome
- [x] Firefox
- [x ] Safari 9
- [x ] Safari 8
- [x ] Safari 7
- [x ] Edge
- [x ] IE 11
- [x ] IE 10

**Comment by tjmonsi** [comment]
No. It should only work on Landing page. The logo should still show on other pages because there's no GDG Philippines logo on other pages. There's a logo on landing page on the banner that's why there's a need to hide at the app-header :)
