### ISSUE TITLE
Progressive App Short Name

### ISSUE THREAD

**Issue by juvarabrera** [gdgphilippines/devfest#134]
### Description
Progressive App's short name is incorrect

### Expected outcome

Short Name is DevFestPH

### Actual outcome

Short Name is DevFestPh

### Steps to reproduce

1. Change lowercase h to uppercase.

### Browsers Affected

- [x ] Chrome
- [x ] Firefox
- [x ] Safari 9
- [ x] Safari 8
- [x ] Safari 7
- [ x] Edge
- [ x] IE 11
- [ x] IE 10

**Comment by tjmonsi** [comment]
To anyone, just change the shortName in both dev.json and prod.json configuration files
