### ISSUE TITLE
optipng Unhandled error event

### ISSUE THREAD

**Issue by jkga** [gdgphilippines/devfest#67]
events.js:160   throw er; // Unhandled 'error' event

Error: spawn /opt/lampp/htdocs/devfest/gulp/node_modules/optipng-bin/vendor/optipng ENOENT

OS: Ubntu 16.04 LTS
yarn : 0.27.5

**Comment by tjmonsi** [comment]
Please check if it is working when you do a yarn install --force on gulp folder
