### ISSUE TITLE
Create a new Speakers Page

### ISSUE THREAD

**Issue by tjmonsi** [gdgphilippines/devfest#75]
### Description
Create a page for the speaker list

Files and assets will be coming from slack channel devfestph care of @juvarabrera 
Content will come from @rap12

**Comment by tjmonsi** [comment]
Connected to https://github.com/gdgphilippines/devfestph2017-files/issues/5

**Comment by juvarabrera** [comment]
1. See speakers section in Home page. Note: There's an inline css inside the section.
2. Change view all button to Speakers page.
3. Move call for speakers to other link
4. Use /speakers for Speakers page. The css used in speakers section in Home page is same here.
5. When a speaker is clicked, go to view speaker profile page. (You decide the url)
6. See /speakers/speaker.html for design. Note: Consider the inline css.

**Comment by tjmonsi** [comment]
Removed the link for safety :)

**Comment by tjmonsi** [comment]
@rap12 @juvarabrera how many speakers should be shown on home page as opposed to showing all?

**Comment by juvarabrera** [comment]
For the home page, show at most 12. If more than 12, show view all button

**Comment by tjmonsi** [comment]
@juvarabrera thanks :)

@rap12 how about the content for this?
