### ISSUE TITLE
Footer redesign

### ISSUE THREAD

**Issue by juvarabrera** [gdgphilippines/devfest#76]
### Description
Change the background color of footer into #333333 and add opacity to the content

### Expected outcome

Footer's background color is #333333 and elements inside has an opacity.
![image](https://user-images.githubusercontent.com/13174418/30248730-2e75339e-9660-11e7-93b1-f74cbb6311fa.png)

### Actual outcome

Footer's background color is blue.

### Live Demo
N/a

### Steps to reproduce

1. footer { background-color: #333 }
2. footer  > (elements inside like text, icons, and images) { opacity: .8 }

### Browsers Affected
- [ x] Chrome
- [x ] Firefox
- [ x] Safari 9
- [ x] Safari 8
- [x ] Safari 7
- [ x] Edge
- [x ] IE 11
- [x ] IE 10

**Comment by juvarabrera** [comment]
Follow up issue. Background color is #333 but has opacity to the element. Tendency is that the background color is #333 but lighter.

**Comment by tjmonsi** [comment]
Ahhh... elements has opacity not the element with background-color. Check
