### ISSUE TITLE
Header font size inside section

### ISSUE THREAD

**Issue by juvarabrera** [gdgphilippines/devfest#77]
### Description

Header 1 is font size is small.

### Expected outcome

Header 1 to have the same font size with header 1 in Tickets page

### Actual outcome

Header 1 has the default font size

### Live Demo
N/A

### Steps to reproduce

1. I don't know how you do this

### Browsers Affected

- [ x] Chrome
- [x ] Firefox
- [x ] Safari 9
- [x ] Safari 8
- [x ] Safari 7
- [x ] Edge
- [x ] IE 11
- [x ] IE 10

**Comment by tjmonsi** [comment]
@juvarabrera where can i find the Header 1?

**Comment by juvarabrera** [comment]
Home page :)

**Comment by tjmonsi** [comment]
Thanks :) will check up on it
