### ISSUE TITLE
Body background

### ISSUE THREAD

**Issue by juvarabrera** [gdgphilippines/devfest#78]
### Description

Body background color is not the same as the footer

### Expected outcome

Body's background color should be the same as the footer's background color, #333333
![image](https://user-images.githubusercontent.com/13174418/30248780-2635afc8-9661-11e7-8056-9d931c97cbc0.png)

### Actual outcome

Has the default background color, white.
![image](https://user-images.githubusercontent.com/13174418/30248777-1a5536f6-9661-11e7-89e8-df46dbdde969.png)

### Live Demo
N/A

### Steps to reproduce

1. body { background-color: #333 }

### Browsers Affected

- [x ] Chrome
- [x ] Firefox
- [x ] Safari 9
- [ x] Safari 8
- [ x] Safari 7
- [ x] Edge
- [x ] IE 11
- [x ] IE 10

**Comment by tjmonsi** [comment]
Is this only for footer or the background of the page? @juvarabrera

**Comment by tjmonsi** [comment]
why should I put background color of body to #333 when it is not going to be seen in any of the pages?
