### ISSUE TITLE
Get tickets incorrect link

### ISSUE THREAD

**Issue by juvarabrera** [gdgphilippines/devfest#81]
### Description
Get tickets link in landing page section is incorrect

### Expected outcome

Redirect to tickets page

### Actual outcome

Redirects to event brite page.

### Live Demo

N/A

### Steps to reproduce

1. Change href to tickets page
2. Remove target attribute

### Browsers Affected

- [x ] Chrome
- [x ] Firefox
- [x ] Safari 9
- [x ] Safari 8
- [x ] Safari 7
- [x ] Edge
- [x ] IE 11
- [x ] IE 10

**Comment by tjmonsi** [comment]
Done in devfestphfiles-2017 repo
