### ISSUE TITLE
Different sizes of  pictures in different browe

### ISSUE THREAD

**Issue by AriadnaSumondong** [gdgphilippines/devfest#84]
### Description
Different sizes of pictures and Google chrome don't have a hamburger.

### Expected outcome

The same sizes

### Actual outcome

Different sizes

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
![firefox](https://user-images.githubusercontent.com/31662702/30250467-5faaa216-9681-11e7-8cf5-748bb1f1737d.png)
702/30250460-40cc736a-9681-11e7-99bc-def284d66244.png)
![googlec](https://user-images.githubusercontent.com/31662702/30250461-40cd8e9e-9681-11e7-9890-8804e6877e89.png)
![microsofte](https://user-images.githubusercontent.com/31662702/30250462-40e223d6-9681-11e7-9bd8-9f113c158d7d.png)

**Comment by tjmonsi** [comment]
Connected to #85
